# example netlify.toml
[build]
  command = "react-scripts build"
  functions = "netlify/functions"
  publish = "build"

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200